## Wayfair ecommerce data analysis

In [2]:
# import packages
import pandas as pd
from data_profiling import ProfileReport

c:\Users\conif\Documents\Projects\Data-Career-School\ecommerce-sales-analysis-datasets\ecommerce-sales-analysis\wayfair-python-analysis\wfvenv\lib\site-packages\tqdm\auto.py:21: TqdmWarning: IProgress not found. Please update jupyter and ipywidgets. See https://ipywidgets.readthedocs.io/en/stable/user_install.html
  from .autonotebook import tqdm as notebook_tqdm

In [ ]:
# import datacustomers = pd.read_csv(r"C:\Users\conif\Documents\Projects\Data-Career-School\ecommerce-sales-analysis-datasets\ecommerce-sales-analysis\data\customers.csv", parse_dates=['signup_date'])

In [8]:
customers.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 3600 entries, 0 to 3599
Data columns (total 4 columns):
 #   Column               Non-Null Count  Dtype
---  ------               --------------  -----
 0   customer_id          3600 non-null   int64
 1   signup_date          3600 non-null   datetime64[ns]
 2   state                3600 non-null   object
 3   acquisition_channel  3600 non-null   object
dtypes: datetime64[ns](1), int64(1), object(2)
memory usage: 112.6+ KB

In [9]:
customers

      customer_id signup_date state acquisition_channel
0               1  2024-09-13    CO      organic_search
1               2  2025-10-21    IL         paid_search
2               3  2025-01-17    AZ            referral
3               4  2024-06-23    FL         paid_social
4               5  2025-04-08    IL         paid_social
...           ...         ...   ...                 ...
3595         3596  2025-11-14    LA            referral
3596         3597  2025-05-27    WA         paid_search
3597         3598  2024-06-03    CA         paid_search
3598         3599  2025-08-23    LA      organic_search
3599         3600  2024-10-19    NY      organic_search

[3600 rows x 4 columns]

In [11]:
c_dupes = customers.duplicated()
print(c_dupes.sum())

0

In [12]:
products = pd.read_csv(r"C:\Users\conif\Documents\Projects\Data-Career-School\ecommerce-sales-analysis-datasets\ecommerce-sales-analysis\data\products.csv")

In [13]:
products.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 90 entries, 0 to 89
Data columns (total 5 columns):
 #   Column        Non-Null Count  Dtype
---  ------        --------------  -----
 0   product_id    90 non-null     int64
 1   product_name  90 non-null     object
 2   category      90 non-null     object
 3   list_price    90 non-null     float64
 4   unit_cost     90 non-null     float64
dtypes: float64(2), int64(1), object(2)
memory usage: 3.6+ KB

In [14]:
p_dupes = products.duplicated()
print(p_dupes.sum())

0

In [17]:
orders = pd.read_csv(r"C:\Users\conif\Documents\Projects\Data-Career-School\ecommerce-sales-analysis-datasets\ecommerce-sales-analysis\data\orders.csv", parse_dates=['order_date'])

In [18]:
orders.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 9245 entries, 0 to 9244
Data columns (total 7 columns):
 #   Column          Non-Null Count  Dtype
---  ------          --------------  -----
 0   order_id        9245 non-null   int64
 1   customer_id     9245 non-null   int64
 2   order_date      9245 non-null   datetime64[ns]
 3   status          9245 non-null   object
 4   payment_method  9245 non-null   object
 5   discount_code   1411 non-null   object
 6   shipping_fee    9245 non-null   float64
dtypes: datetime64[ns](1), float64(1), int64(2), object(3)
memory usage: 505.7+ KB

In [19]:
orders.isna().sum()

order_id             0
customer_id          0
order_date           0
status               0
payment_method       0
discount_code     7834
shipping_fee         0
dtype: int64

In [20]:
o_dupes = orders.duplicated()
print(o_dupes.sum())

38

In [21]:
orders

,order_id,customer_id,order_date,status,payment_method,discount_code,shipping_fee
0,100001,1530,2024-01-01 09:24:45,completed,credit_card,NaN,6.95
1,100002,3531,2024-01-01 10:37:49,completed,credit_card,NaN,0.00
2,100003,840,2024-01-01 10:59:09,completed,credit_card,NaN,0.00
3,100004,725,2024-01-01 12:48:34,completed,apple_pay,WELCOME10,0.00
4,100005,3452,2024-01-01 17:44:03,completed,gift_card,NaN,0.00
...,...,...,...,...,...,...,...
9240,109203,3499,2025-12-31 16:50:18,completed,credit_card,HOLIDAY20,6.95
9241,109204,3410,2025-12-31 17:40:58,completed,credit_card,HOLIDAY20,0.00
9242,109205,2911,2025-12-31 18:21:51,completed,credit_card,NaN,0.00
9243,109206,1157,2025-12-31 21:38:59,completed,credit_card,NaN,6.95
9244,109207,2208,2025-12-31 23:23:29,completed,paypal,HOLIDAY20,0.00

In [25]:
print(o_dupes)

0       False
1       False
2       False
3       False
4       False
        ...
9240    False
9241    False
9242    False
9243    False
9244    False
Length: 9245, dtype: bool